#!/bin/bash
cat <<'EOF'
Solution notes — Question 5 | Kubectl sorting

A good resources here (and for many other things) is the kubectl-cheat-sheet. You can reach it fast when searching for "cheat sheet" in the Kubernetes docs.

 

###### **Step 1**

\# cka8448:/opt/course/5/find_pods.sh

kubectl get pod -A --sort-by=.metadata.creationTimestamp

We should be able to execute it and see sorting by AGE:

NAMESPACE     NAME                                       READY   ...

kube-system   kube-proxy-dvv7m                           1/1     ...

kube-system   weave-net-gjrxh                            2/2     ...

kube-system   etcd-cka8448                               1/1     ...

kube-system   kube-apiserver-cka8448                     1/1     ...

kube-system   kube-scheduler-cka8448                     1/1     ...

kube-system   kube-controller-manager-cka8448            1/1     ...

default       berlin-external-monitor-6c8fd896dd-66tvw   1/1     ...

default       berlin-external-proxy-98bccbc68-59gjg      1/1     ...

default       berlin-external-proxy-98bccbc68-phpvt      1/1     ...

kube-system   coredns-6f8b9d9f4b-8z7rb                   1/1     ...

kube-system   coredns-6f8b9d9f4b-fg7bt                   1/1     ...

 

###### **Step 2**

For the second command we create file:

\# cka8448:/opt/course/5/find_pods_uid.sh

kubectl get pod -A --sort-by=.metadata.uid

When we execute we should see a different sorting order:

NAMESPACE     NAME                                       READY   ...

kube-system   kube-proxy-dvv7m                           1/1     ...

kube-system   coredns-6f8b9d9f4b-8z7rb                   1/1     ...

default       berlin-external-monitor-6c8fd896dd-66tvw   1/1     ...

default       berlin-external-proxy-98bccbc68-59gjg      1/1     ...

default       berlin-external-proxy-98bccbc68-phpvt      1/1     ...

kube-system   kube-controller-manager-cka8448            1/1     ...

kube-system   kube-scheduler-cka8448                     1/1     ...

kube-system   kube-apiserver-cka8448                     1/1     ...

kube-system   etcd-cka8448                               1/1     ...

kube-system   coredns-6f8b9d9f4b-fg7bt                   1/1     ...

kube-system   weave-net-gjrxh                            2/2     ...
EOF
